FORMAT: 1A
HOST: https://modulus-dev.openmrs.org/

# Modulus API

Modulus, the OpenMRS Modules directory, has a full-featured REST API able to
read, create, and manipulate data surrounding OpenMRS Modules.

We know this API is full-featured because we use it:
[Modulus UI](https://github.com/openmrs/openmrs-contrib-modulus-ui), the web 
interface for OpenMRS Modules, communicates exclusively through this API.

You are welcome and encouraged to set up your own server running Modulus Core
and Modulus UI for development. However, to build an application that uses
OpenMRS Modules production data, **you must register as a Modulus developer**.
To register, send an email to [helpdesk@openmrs.org](mailto:helpdesk@openmrs.org)
requesting a Modulus API key.

Happy hacking! For information and feedback, consult the [Modulus category on
OpenMRS Talk](https://talk.openmrs.org/category/projects/modulus).

This documentation is available on GitHub. To change or improve these docs, fork
[elliottwilliams/openmrs-contrib-modulus-docs](https://github.com/elliottwilliams/openmrs-contrib-modulus-docs)
and submit a pull request.

![the Modulus Guitar](guitar.jpg) 
